[package]
name = "rust_tetris"
version = "0.9.0"
edition = "2021"
authors = ["杨昊辰"]
description = "A Tetris game written in Rust using ggez"
license = "MIT OR Apache-2.0"
repository = "https://github.com/S0nrEir/rust_tetris"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.1"
num_enum = "0.7.3"
colored = "2.0"
rand = "0.8"

[features]
# 调试模式
debug = []
# 进入绘制测试流程 / Enter debug drawing mode
debug_draw = []

[profile.dev]  
debug = true
opt-level = 0

[profile.dev.package."*"]  
opt-level = 0