[package]
name = "rust_tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.0"
num_enum = "0.7.3"
colored = "2.0"
rand = "0.8"

[features]
# 调试模式
debug = []
# 进入绘制测试流程 / Enter debug drawing mode
debug_draw = []

[profile.dev]  
debug = true  
opt-level = 0

[profile.dev.package."*"]  
opt-level = 0